[package]
name = "branec_tokens"
version = "0.1.0"
edition = "2024"

[dependencies]
branec_source = { path = "../branec_source/" }
branec_symbols = { path = "../branec_symbols/" }

chumsky.workspace = true
