[package]
name = "brane_script_llvm_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
brane_script_common = { path="../../../../brane_script_common/" }

inkwell = { version = "0.5.0", features = ["llvm18-0"] }
llvm-sys = "180.0.0"
anyhow.workspace = true
defer.workspace = true

